#!/bin/bash
# SHAR-X AI Startup Script - Phase 1

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                        SHAR-X AI - PHASE 1 STARTUP                         ║"
echo "║              The Future of Intelligent Assistance                           ║"
echo "║                  A Machine-Mind, Awakened.                                 ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Choose startup method:"
echo ""
echo "Option 1: Docker (Recommended - easiest)"
echo "  $ docker-compose up --build"
echo ""
echo "Option 2: Local Development (Manual)"
echo ""
echo "  Backend (Terminal 1):"
echo "  $ cd backend"
echo "  $ python -m venv venv"
echo "  $ source venv/bin/activate         # or 'venv\Scripts\activate' on Windows"
echo "  $ pip install -r requirements.txt"
echo "  $ cp .env.example .env"
echo "  $ python -m uvicorn app.main:app --reload"
echo ""
echo "  Frontend (Terminal 2):"
echo "  $ cd frontend"
echo "  $ npm install"
echo "  $ npm run dev"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "After startup, access the application at:"
echo "  Frontend:     http://localhost:5173"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/docs"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Prerequisites for local development:"
echo "  - Python 3.11+"
echo "  - Node.js 18+"
echo "  - Ollama with neural-chat model (or set GEMINI_API_KEY/OPENAI_API_KEY in .env)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
